version: '3.8'

services:
    postgres:
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: graphql
        image: postgres:14
        ports:
            - '5432:5432'
        volumes:
            - db-data:/var/lib/postgresql/data

volumes:
    db-data:
        driver: local